server:
  port: 8088
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    cache: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.138:3306/webdb
    username: pmguser
    password: pmgk1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect   #queryDsl연동을 위해 버전을 낮춰야 했다.
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging.level:
  com.workbook.controller : debug
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

#swagger
springdoc:
  api-docs:
    enabled: true  # API 문서 활성화 여부
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로 설정
    operationsSorter: method  # 메서드 기준 정렬
    tagsSorter: alpha  # 태그를 알파벳 순서로 정렬